CREATE TABLE IF NOT EXISTS Tree (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    homePersonID INTEGER,
    FOREIGN KEY(homePersonID) REFERENCES Person(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Person (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    treeID INTEGER NOT NULL,
    firstName TEXT NOT NULL,
    lastName TEXT NOT NULL,
    gender TEXT NOT NULL CHECK(gender IN ('Male', 'Female', 'Unknown')),
    birthDate DATE,
    FOREIGN KEY(treeID) REFERENCES Tree(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Family (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    treeID INTEGER NOT NULL,
    fatherID INTEGER,
    motherID INTEGER,
    FOREIGN KEY(treeID) REFERENCES Tree(id) ON DELETE CASCADE,
    FOREIGN KEY(fatherID) REFERENCES Person(id) ON DELETE SET NULL,
    FOREIGN KEY(motherID) REFERENCES Person(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS FamilyChild (
    childID INTEGER NOT NULL,
    familyID INTEGER NOT NULL,
    FOREIGN KEY(childID) REFERENCES Person(id) ON DELETE CASCADE,
    FOREIGN KEY(familyID) REFERENCES Family(id) ON DELETE CASCADE,
    PRIMARY KEY (childID, familyID)
);
